services:
  - type: web
    name: bright-ears
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn web_app:app"
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bright-ears-db
          property: connectionString
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: bright-ears-db
    databaseName: bright_ears
    user: bright_ears_user
    plan: free